#import <CoreGraphics/CGGeometry.h>
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIAXElement.h"

@interface UIAXElement : NSObject <UIAXElement>
{
    struct __AXUIElement *_axuiElementRef;
    double _creationTime;
    double _lastAccessedTime;
    BOOL _isValid;
    long _axError;
}

+ (CGRect)_convertHostedViewFrame:(CGRect)arg1 forContextID:(id)arg2;
+ (CGPoint)_convertHostedCoordinates:(CGPoint)arg1 forContextID:(id)arg2;
+ (CGRect)_convertRectFromScreenToDevice:(CGRect)arg1;
+ (CGRect)_convertRectFromDeviceToScreen:(CGRect)arg1;
+ (CGPoint)_convertPointFromScreenToDevice:(CGPoint)arg1;
+ (CGPoint)_convertPointFromDeviceToScreen:(CGPoint)arg1;
+ (id)stringForTraits:(unsigned long long)arg1;
+ (id)stringForAXNotification:(NSInteger)arg1;
+ (id)stringForAXError:(long)arg1;
+ (id)uiaxAccessibilityUIServerElement;
+ (id)uiaxFocusedApplicationElement;
+ (id)uiaxSpringBoardElement;
+ (id)uiaxSystemApplicationElement;
+ (id)uiaxSystemWideElement;
+ (id)uiaxElementAtPosition:(CGPoint)arg1;
+ (id)uiaxApplicationAtPosition:(CGPoint)arg1;
+ (id)_objectForCFTypeRef:(void *)arg1;
+ (NSInteger)_parameterizedAttributeForString:(id)arg1;
+ (id)_stringForParameterizedAttribute:(NSInteger)arg1;
+ (NSInteger)_attributeForString:(id)arg1;
+ (id)_stringForAttribute:(NSInteger)arg1;
+ (id)_stringsForTraitsDictionary;
+ (id)_parameterizedAttributesForStringsDictionary;
+ (id)_stringsForParameterizedAttributesDictionary;
+ (id)_regularAttributesForStringsDictionary;
+ (id)_stringsForRegularAttributesDictionary;
+ (id)_traitStrings;
+ (id)_traitNumbers;
+ (id)_parameterizedAttributeStrings;
+ (id)_parameterizedAttributeNumbers;
+ (id)_regularAttributeStrings;
+ (id)_regularAttributeNumbers;
+ (id)uiaxElementWithAXUIElementRef:(struct __AXUIElement *)arg1;
+ (BOOL)unregisterObserver:(struct __AXObserver *)arg1 forAXNotification:(NSInteger)arg2;
+ (BOOL)registerObserver:(struct __AXObserver *)arg1 forAXNotification:(NSInteger)arg2;
+ (BOOL)registerObserver:(struct __AXObserver *)arg1 forAXNotifications:(BOOL)arg2;
+ (void)_raiseIfAXErrorAPIDisabled:(long)arg1;
+ (void)_raiseAXErrorAPIDisabled;
+ (void)initializeAccessibility;
+ (void)initialize;
- (void)logAXTree;
- (void)logAXAncestry;
- (void)logAXInfo;
- (BOOL)_hasNonzeroFrame;
- (id)ancestry;
- (id)descendantWithTestingTrait:(id)arg1;
- (id)descendantsWithAttributes:(id)arg1 traits:(unsigned long long)arg2;
- (id)descendants;
- (id)childWithTestingTrait:(id)arg1;
- (id)children;
- (id)responder;
- (id)parent;
- (id)firstElementOfAttribute:(NSInteger)arg1 withValue:(id)arg2 forAttribute:(NSInteger)arg3;
- (id)uiaxElementAtCenterPoint;
- (id)centerPoint;
- (id)hitpoint;
- (BOOL)_isVisibleAtPoint:(CGPoint)arg1;
- (id)rect;
- (id)description;
- (unsigned long long)traits;
- (id)traitsNumber;
- (id)_copyTraitsNumber;
- (id)stringForAllKnownAttributes;
- (id)stringForAttributes:(id)arg1;
- (id)valuesForAllKnownAttributes;
- (BOOL)checkIsValid;
- (BOOL)isValid;
- (long)axError;
- (NSInteger)pid;
- (BOOL)performAXAction:(NSInteger)arg1 withValue:(id)arg2;
- (BOOL)performAXAction:(NSInteger)arg1;
- (id)valueForUndefinedKey:(id)arg1;
- (id)valueForKey:(id)arg1;
- (id)valueForAttribute:(NSInteger)arg1 parameter:(id)arg2;
- (id)valuesForAttributes:(id)arg1;
- (BOOL)setValue:(id)arg1 forAttribute:(NSInteger)arg2;
- (id)valueForAttribute:(NSInteger)arg1;
- (struct __AXUIElement *)axuiElementRef;
- (NSUInteger)hash;
- (BOOL)isEqual:(id)arg1;
- (void)finalize;
- (void)dealloc;
- (void)_setLastAccessedTime:(double)arg1;
- (double)_lastAccessedTime;
- (double)_creationTime;
- (id)_initWithAXUIElementRef:(struct __AXUIElement *)arg1;
- (void)_setValidForAXError:(long)arg1;
- (void)_invalidate;

@end

