#import <CoreGraphics/CGGeometry.h>
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@class NSInvocation;

@interface UIAElementArray : NSArray
{
    NSArray *_array;
    NSInvocation *_selfPatienceInvocation;
    double _refreshedTime;
    double _lastAccessedTime;
}

+ (void)_removeCachedArrayAtPtr:(id *)arg1;
+ (void)_cacheArray:(id)arg1 atPtr:(id *)arg2;
+ (id)_cachedArrayAtPtr:(id *)arg1;
+ (id)_arrayWithArray:(id)arg1;
+ (NSInteger)_maxCount;
+ (NSInteger)_liveCount;
+ (void)initialize;
- (BOOL)isValid;
- (id)scriptingInvocationFullExpressionString;
- (id)scriptingInvocationString;
- (id)scriptingIndexSynonymsForElement:(id)arg1;
- (id)scriptingFavoredIndexSynonymForElement:(id)arg1;
- (id)_scriptingIndexSynonymsForElement:(id)arg1 maxCount:(NSUInteger)arg2;
- (id)elementOfClass:(Class)arg1 atIndex:(NSUInteger)arg2;
- (void)logElementTrees;
- (void)logElements;
- (id)firstWithPredicate:(id)arg1;
- (id)firstWithValue:(id)arg1 forKey:(id)arg2;
- (id)firstWithName:(id)arg1;
- (id)withPredicate:(id)arg1;
- (id)withValue:(id)arg1 forKey:(id)arg2;
- (id)withName:(id)arg1;
- (id)withClass:(Class)arg1;
- (id)_withPredicate:(id)arg1;
- (id)_withValue:(id)arg1 forKey:(id)arg2;
- (id)_withName:(id)arg1;
- (void)_logLocalizedStringHintForKey:(id)arg1 testValue:(id)arg2;
- (id)_withClass:(Class)arg1;
- (BOOL)_isStillFreshAtTime:(double)arg1;
- (void)_setLastAccessedTime:(double)arg1;
- (double)_lastAccessedTime;
- (double)_refreshedTime;
- (void)_setArray:(id)arg1;
- (id)nsArray;
- (id)_objectWithPatienceInvocationFromUIAObject:(id)arg1 selector:(SEL)arg2;
- (void)_setSelfPatienceInvocation:(id)arg1;
- (id)_selfPatienceInvocation;
- (id)description;
- (NSUInteger)hash;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isEqualToArray:(id)arg1;
- (id)objectAtIndex:(NSUInteger)arg1;
- (NSUInteger)count;
- (void)dealloc;
- (id)_initWithArray:(id)arg1;

@end

