#import <CoreGraphics/CGGeometry.h>
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIASyntheticEvents;

@interface UIARemote : NSObject
{
    UIASyntheticEvents *_eventGenerator;
}

+ (id)sharedRemote;
@property(readonly) UIASyntheticEvents *eventGenerator; // @synthesize eventGenerator=_eventGenerator;
- (void)dragFrom:(id)arg1 to:(id)arg2 forDuration:(id)arg3;
- (_Bool)_dragFrom:(id)arg1 to:(id)arg2 forDuration:(NSTimeInterval)arg3 withTouchCount:(NSInteger)arg4 withFlick:(_Bool)arg5;
- (void)tap:(id)arg1;
- (_Bool)_tapAtPoint:(id)arg1 tapCount:(double)arg2 touchCount:(double)arg3;
- (void)clickVolumeDown;
- (void)holdVolumeDown:(double)arg1;
- (void)clickVolumeUp;
- (void)holdVolumeUp:(double)arg1;
- (void)clickHome;
- (void)holdHome:(double)arg1;
- (void)clickMicrophone;
- (void)holdMicrophone:(double)arg1;
- (void)clickPlayPause;
- (void)holdPlayPause:(double)arg1;
- (void)clickMenu;
- (void)holdMenu:(double)arg1;
- (void)clickSelect;
- (void)holdSelect:(double)arg1;
- (void)clickRight;
- (void)holdRight:(double)arg1;
- (void)clickLeft;
- (void)holdLeft:(double)arg1;
- (void)clickDown;
- (void)holdDown:(double)arg1;
- (void)clickUp;
- (void)holdUp:(double)arg1;
- (void)dealloc;
- (id)init;

@end

