#import <CoreGraphics/CGGeometry.h>
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIAutomation/UIASyntheticEvents.h>

@interface UIASyntheticTVRemoteEvents : UIASyntheticEvents
{
}

+ (id)sharedEventGenerator;
- (struct __IOHIDEvent *)_UIACreateIOHIDEventType:(NSUInteger)arg1;
- (BOOL)_isEdgePoint:(CGPoint)arg1;

@end

