#import <CoreGraphics/CGGeometry.h>
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIAutomation/UIAElement.h>

@class CLSimulationManager, NSDate, NSString, UIAHost, UIASyntheticEvents, UIASyntheticStarkEvents;

@interface UIATarget : UIAElement
{
    NSDate *_startupDate;
    int _textViewValueMaxLength;
    int _interfaceOrientation;
    double _lastAnimationEndedTime;
    NSString *_nameOfLastApp;
    UIAHost *_host;
    CLSimulationManager *_locationSimulationManager;
    BOOL _logElementTakesScreenshot;
    BOOL _handlesAlerts;
    unsigned int valueChangedCount;
    UIASyntheticEvents *_eventGenerator;
    UIASyntheticStarkEvents *_starkEventGenerator;
}

+ (id)toManyRelationshipKeys;
+ (id)toOneRelationshipKeys;
+ (id)attributeKeys;
+ (id)_locationForObject:(id)arg1 withOptions:(id)arg2;
+ (id)localTarget;
@property(readonly) UIASyntheticStarkEvents *starkEventGenerator; // @synthesize starkEventGenerator=_starkEventGenerator;
@property(readonly) UIASyntheticEvents *eventGenerator; // @synthesize eventGenerator=_eventGenerator;
@property unsigned int valueChangedCount; // @synthesize valueChangedCount;
@property BOOL handlesAlerts; // @synthesize handlesAlerts=_handlesAlerts;
@property BOOL logElementTakesScreenshot; // @synthesize logElementTakesScreenshot=_logElementTakesScreenshot;
- (BOOL)reactivateApp;
- (BOOL)deactivateApp;
- (BOOL)deactivateAppForDuration:(id)arg1;
- (BOOL)unlock;
- (BOOL)unlockWithOptions:(id)arg1;
- (void)_enterPasscode:(id)arg1;
- (void)_tapPictureFrame:(id)arg1;
- (void)_slideToHandoff:(id)arg1;
- (void)_slideToCamera:(id)arg1;
- (void)_slideToUnlock:(id)arg1;
- (id)_lockScreenScrollView;
- (BOOL)lock;
- (BOOL)lockForDuration:(id)arg1;
- (BOOL)isScreenOff;
- (BOOL)isLocked;
- (void)setRinger:(id)arg1;
- (void)holdVolumeDown:(id)arg1;
- (void)clickVolumeDown;
- (void)holdVolumeUp:(id)arg1;
- (void)clickVolumeUp;
- (void)holdLock:(id)arg1;
- (void)clickLock;
- (void)holdMenu:(id)arg1;
- (void)clickMenu;
- (void)shake;
- (void)rotate:(id)arg1 withOptions:(id)arg2;
- (void)pinchOpenFrom:(id)arg1 to:(id)arg2 forDuration:(id)arg3;
- (void)pinchCloseFrom:(id)arg1 to:(id)arg2 forDuration:(id)arg3;
- (void)flickFrom:(id)arg1 to:(id)arg2;
- (void)dragFrom:(id)arg1 to:(id)arg2 forDuration:(id)arg3;
- (void)touch:(id)arg1 andHold:(id)arg2;
- (void)touch:(id)arg1 withOptions:(id)arg2;
- (void)touch:(id)arg1;
- (BOOL)_touch:(id)arg1 withOptions:(id)arg2;
- (void)tap:(id)arg1 withOptions:(id)arg2;
- (void)twoFingerTap:(id)arg1;
- (void)doubleTap:(id)arg1;
- (void)tap:(id)arg1;
- (BOOL)_dragFrom:(id)arg1 to:(id)arg2 forDuration:(NSTimeInterval)arg3 withTouchCount:(NSInteger)arg4 withFlick:(BOOL)arg5;
- (BOOL)_tapRequiredObject:(id)arg1 tapCount:(double)arg2 touchCount:(double)arg3;
- (BOOL)_tapOptionalObject:(id)arg1 tapCount:(double)arg2 touchCount:(double)arg3 tapOffset:(id)arg4;
- (id)localizedStringForKey:(id)arg1 value:(id)arg2 table:(id)arg3 bundlePath:(id)arg4;
- (id)localizedStringForKey:(id)arg1 withOptions:(id)arg2;
- (id)localizedStringForKey:(id)arg1;
- (id)scriptingSynonymStrings;
- (id)scriptingSynonyms;
- (id)scriptingFavoredSynonymString;
- (BOOL)_trackValueChanges:(BOOL)arg1;
- (BOOL)_handleAnnouncement:(id)arg1;
- (BOOL)_handleAlert;
- (void)setPassiveEventListeningMode:(id)arg1 withDelay:(id)arg2;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (NSUInteger)verboseOptions;
- (void)setVerboseOptions:(NSUInteger)arg1;
- (BOOL)delayForTimeInterval:(double)arg1;
- (double)popPatience;
- (void)pushPatience:(double)arg1;
- (void)setPatience:(double)arg1;
- (double)patience;
- (id)uiaxSpringBoardElement;
- (id)uiaxSystemAppElement;
- (id)uiaxSystemWideElement;
- (id)elements;
- (id)hardwareKeyboard;
- (id)remote;
- (id)mainScreen;
- (id)accessibilityUI;
- (id)springboard;
- (id)systemApp;
- (id)foregroundApps;
- (id)frontMostApp;
- (id)applicationAtPoint:(id)arg1;
- (id)_applicationAtPosition:(CGPoint)arg1;
- (id)applications;
- (id)host;
- (void)setTextViewValueMaxLength:(NSInteger)arg1;
- (NSInteger)textViewValueMaxLength;
- (void)setTargetClipboard:(id)arg1;
- (id)targetClipboard;
- (void)captureStarkRect:(id)arg1 withName:(id)arg2;
- (void)captureRect:(id)arg1 withName:(id)arg2;
- (void)captureRect:(id)arg1 onScreen:(id)arg2 withName:(id)arg3;
- (id)imageFromRect:(CGRect)arg1;
- (void)captureStarkScreenWithName:(id)arg1;
- (void)captureScreenWithName:(id)arg1;
- (id)lastCommandTime;
- (double)upTime;
- (id)startupDate;
- (BOOL)setLocation:(id)arg1 withOptions:(id)arg2;
- (BOOL)setLocation:(id)arg1;
- (BOOL)setDeviceOrientation:(id)arg1;
- (id)deviceOrientation;
- (id)localeName;
- (id)localeID;
- (id)languageName;
- (id)languageID;
- (id)uniqueIdentifier;
- (id)systemBuild;
- (id)systemVersion;
- (id)systemName;
- (id)model;
- (id)name;
- (id)rect;
- (BOOL)checkIsValid;
- (BOOL)isValid;
- (NSUInteger)hash;
- (BOOL)isEqual:(id)arg1;
- (void)_setLastAnimationEndedTime:(double)arg1;
- (double)_lastAnimationEndedTime;
- (NSInteger)_interfaceOrientation;
- (void)_updateInterfaceOrientation;
- (void)_invalidate;
- (void)dealloc;
- (id)init;
- (id)_systemVersionDictionary;

@end

